import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import net from 'node:net';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

let child; let base; let temp;
async function freePort() { const server = net.createServer(); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); const port = server.address().port; server.close(); return port; }
async function waitReady() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(`${base}/api/health`)).ok) return; } catch {} await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Server did not become ready.'); }

test.before(async () => { const port = await freePort(); base = `http://127.0.0.1:${port}`; temp = fs.mkdtempSync(path.join(os.tmpdir(), 'firstflush-')); child = spawn(process.execPath, ['server.js'], { cwd: path.resolve('.'), env: { ...process.env, PORT: String(port), CORS_ORIGINS: base, OPEN_METEO_BASE_URL: 'http://127.0.0.1:1', FIRSTFLUSH_RUNTIME_FILE: path.join(temp, 'runtime.json'), FIRSTFLUSH_UPLOAD_DIR: path.join(temp, 'uploads') }, stdio: 'ignore' }); await waitReady(); });
test.after(() => { child?.kill('SIGTERM'); fs.rmSync(temp, { recursive: true, force: true }); });

test('health, methodology, and system endpoints work', async () => { const health = await (await fetch(`${base}/api/health`)).json(); assert.equal(health.ok, true); const methodology = await (await fetch(`${base}/api/methodology`)).json(); assert.equal(methodology.weights.dryPeriod, 0.22); const system = await (await fetch(`${base}/api/system`)).json(); assert.equal(system.storage, 'JSON file'); });
test('state contains ranked risk and explicit fallback weather', async () => { const body = await (await fetch(`${base}/api/state`)).json(); assert.equal(body.locations.length, 5); assert.ok(body.locations[0].rank === 1); assert.ok(['live', 'cached', 'fallback'].includes(body.weather.mode)); assert.ok(body.locations[0].factors.rainfall >= 0); });
test('filters return matching locations', async () => { const body = await (await fetch(`${base}/api/state?state=Karnataka&city=Bengaluru`)).json(); assert.equal(body.locations.length, 1); assert.equal(body.locations[0].state, 'Karnataka'); });
test('invalid observation and duplicate observation are handled', async () => { const invalid = await fetch(`${base}/api/observations`, { method: 'POST', body: (() => { const form = new FormData(); form.set('locationId', 'IN-001'); form.set('type', 'Invalid'); return form; })() }); assert.equal(invalid.status, 400); const form = new FormData(); form.set('locationId', 'IN-001'); form.set('type', 'Blocked drain'); form.set('severity', 'high'); form.set('blockageLevel', '80'); const created = await fetch(`${base}/api/observations`, { method: 'POST', body: form }); assert.equal(created.status, 201); const duplicate = await fetch(`${base}/api/observations`, { method: 'POST', body: form }); assert.equal(duplicate.status, 409); });
test('observation verification changes state', async () => { const observations = await (await fetch(`${base}/api/observations`)).json(); const item = observations[0]; const response = await fetch(`${base}/api/observations/${item.id}/verify`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ verification: 'Verified', reviewer: 'Test operator', comment: 'Checked.' }) }); assert.equal(response.status, 200); assert.equal((await response.json()).verification, 'Verified'); });
test('action lifecycle and evidence endpoint work', async () => { const created = await fetch(`${base}/api/actions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ locationId: 'IN-001', type: 'Inspect', priority: 'Critical' }) }); assert.equal(created.status, 201); const action = await created.json(); const updated = await fetch(`${base}/api/actions/${action.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status: 'Completed' }) }); assert.equal((await updated.json()).status, 'Completed'); });
test('Copilot and reports work', async () => { const chat = await (await fetch(`${base}/api/chat`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message: 'Which drain should we inspect first?' }) })).json(); assert.equal(chat.mode, 'local-grounded'); assert.match(chat.answer, /risk/i); const csv = await (await fetch(`${base}/api/report.csv`)).text(); assert.match(csv, /riskScore/); const report = await (await fetch(`${base}/api/report.json`)).json(); assert.equal(Array.isArray(report.locations), true); });
