import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import serverless from 'serverless-http';

const root=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const port=Number(process.env.PORT||8787);
const runtimePath=path.resolve(process.env.FIRSTFLUSH_RUNTIME_FILE||path.join(root,'data/runtime.json'));
const seedPath=path.resolve(process.env.FIRSTFLUSH_SEED_FILE||path.join(root,'data/locations.json'));
const uploadDir=path.resolve(process.env.FIRSTFLUSH_UPLOAD_DIR||path.join(root,'uploads'));
fs.mkdirSync(path.dirname(runtimePath),{recursive:true}); fs.mkdirSync(uploadDir,{recursive:true});
const seed=JSON.parse(fs.readFileSync(seedPath,'utf8'));
let db=fs.existsSync(runtimePath)?JSON.parse(fs.readFileSync(runtimePath,'utf8')):{locations:seed,observations:[],actions:[],events:[],weather:{},updatedAt:new Date().toISOString()};
const clients=new Set(); const id=()=>crypto.randomUUID(); const now=()=>new Date(); const iso=()=>now().toISOString();
const weights={dryPeriod:.22,rainfall:.22,pavedSurface:.14,traffic:.12,construction:.10,waste:.08,blockage:.07,waterBodyProximity:.05};
const clamp=(v)=>Math.max(0,Math.min(100,Number(v)||0)); const clean=(v,n=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
const validCoords=(lat,lon)=>Number.isFinite(Number(lat))&&Number(lat)>=6&&Number(lat)<=38&&Number(lon)>=68&&Number(lon)<=98;
function persist(){db.updatedAt=iso();fs.writeFileSync(runtimePath,JSON.stringify(db,null,2));}
function emit(type,payload={}){const event={id:id(),type,at:iso(),payload};db.events.unshift(event);db.events=db.events.slice(0,200);persist();const msg=`event: ${type}\ndata: ${JSON.stringify(payload)}\n\n`;for(const c of clients){try{c.write(msg)}catch{clients.delete(c)}}}
function level(s){return s>=75?'Very high':s>=50?'High':s>=25?'Moderate':'Low'}
function rainScore(w){return clamp((Number(w?.rainfallAmount)||0)*4)*.45+clamp(w?.rainfallIntensity)*.35+clamp(w?.rainfallProbability)*.2}
function waterScore(m){m=Number(m);if(m<=50)return 100;if(m<=100)return 90;if(m<=250)return 75;if(m<=500)return 55;if(m<=1000)return 35;return 15}
function risk(loc,weather=null){const obs=db.observations.filter(o=>o.locationId===loc.id);const latest=obs[0];const factors={dryPeriod:clamp(Number(loc.dryDays)*5.55),rainfall:rainScore(weather),pavedSurface:clamp(loc.paved),traffic:clamp(loc.traffic),construction:clamp(loc.construction),waste:clamp(Math.max(loc.waste||0,latest?.visibleLitter?60:0,latest?.oilResidue?75:0,latest?.constructionSediment?55:0,latest?.animalWaste?45:0)),blockage:clamp(Math.max(loc.blockage||0,latest?.blockageLevel||0)),waterBodyProximity:waterScore(loc.distanceToWaterBody)};const score=Math.round(Object.entries(weights).reduce((s,[k,w])=>s+factors[k]*w,0));const conf=clamp((loc.coverage==='Verified'?35:loc.coverage==='Community reported'?25:loc.coverage==='Estimated'?15:8)+(weather?.mode==='live'?30:weather?.mode==='cached'?20:weather?.mode==='fallback'?8:0)+(obs.length?25:0)+(loc.waterBodyVerified?10:0));const reasons=[];if(factors.dryPeriod>70)reasons.push(`${loc.dryDays} dry days`);if(factors.rainfall>70)reasons.push('substantial forecast rainfall');if(factors.pavedSurface>70)reasons.push('large paved catchment');if(factors.traffic>70)reasons.push('high traffic exposure');if(factors.construction>60)reasons.push('construction exposure');if(factors.waste>55)reasons.push('waste exposure');if(factors.blockage>55)reasons.push('recent blockage/debris evidence');if(factors.waterBodyProximity>70)reasons.push('close water-body connection');return {...loc,riskScore:score,level:level(score),confidence:conf>=75?'High':conf>=50?'Medium':'Low',confidenceScore:conf,factors,reason:`${loc.name} is ${level(score).toLowerCase()} priority because of ${reasons.join(', ')||'limited available evidence'}.`,recommendation:score>=75?'Inspect and clear visible debris before rainfall; use a temporary screen only if safe and permitted.':score>=50?'Schedule an inspection before rainfall.':'Monitor and verify the latest condition.',evidenceFreshness:latest?Math.round((now()-new Date(latest.observedAt))/3600000)+'h old':'No recent evidence',weatherStatus:weather?.mode||'offline',weatherProvider:weather?.provider||'Unavailable',weatherUpdatedAt:weather?.updatedAt||null,interventionStatus:db.actions.find(a=>a.locationId===loc.id&& !['Verified','Rejected'].includes(a.status))?.status||loc.interventionStatus||'No active intervention',calculatedAt:iso()}}
async function weather(lat,lon){if(!validCoords(lat,lon))return{mode:'offline',provider:'Unavailable',error:'Use an Indian latitude and longitude.'};const key=`${Number(lat).toFixed(2)},${Number(lon).toFixed(2)}`;const cached=db.weather[key];try{const base=process.env.OPEN_METEO_BASE_URL||'https://api.open-meteo.com/v1/forecast';const r=await fetch(`${base}?latitude=${lat}&longitude=${lon}&hourly=precipitation,precipitation_probability,rain&forecast_days=1&timezone=auto`);if(!r.ok)throw Error('provider');const d=await r.json();const p=d.hourly?.precipitation||[];const pp=d.hourly?.precipitation_probability||[];const amount=Math.max(...p.slice(0,6),0);const probability=Math.max(...pp.slice(0,6),0);const result={mode:'live',provider:'Open-Meteo',updatedAt:iso(),rainfallAmount:Number(amount.toFixed(1)),rainfallIntensity:clamp(amount*8),rainfallProbability:probability,forecastWindow:'next 6 hours',timezone:d.timezone};db.weather[key]=result;persist();emit('weather.updated',result);return result}catch(e){if(cached){const age=now()-new Date(cached.updatedAt);return {...cached,mode:'cached',ageMs:age,stale:age>Number(process.env.WEATHER_STALE_MS||3600000)}}return{mode:'fallback',provider:'Local scenario',updatedAt:iso(),rainfallAmount:18,rainfallIntensity:70,rainfallProbability:70,forecastWindow:'demo fallback',stale:true,note:'Provider unavailable; this is not live weather.'}}
}
const origins=String(process.env.CORS_ORIGINS||'http://localhost:8787').split(',').map(s=>s.trim());app.use(cors({origin:(o,cb)=>!o||origins.includes('*')||origins.includes(o)?cb(null,true):cb(Error('CORS denied'))}));app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(root,'public')));app.use('/uploads',express.static(uploadDir));
const upload=multer({dest:uploadDir,limits:{fileSize:Number(process.env.MAX_UPLOAD_BYTES||5242880),files:Number(process.env.MAX_UPLOAD_FILES||3)},fileFilter:(_r,f,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(f.mimetype))});
app.get('/api/health',(_q,res)=>res.json({ok:true,service:'firstflush-api',mode:'local-json-adapter',updatedAt:db.updatedAt}));
app.get('/api/system',(_q,res)=>res.json({mode:'local',storage:'JSON file',coverage:'Limited demo records',updatedAt:db.updatedAt,events:db.events.slice(0,20)}));
app.get('/api/methodology',(_q,res)=>res.json({weights,disclaimer:'Relative prioritization only; not laboratory pollution measurement.',levels:{Low:'0-24',Moderate:'25-49',High:'50-74','Very high':'75-100'}}));
app.get('/api/weather',async(req,res)=>res.json(await weather(Number(req.query.lat||20.5937),Number(req.query.lon||78.9629))));
app.get('/api/state',async(req,res)=>{const all=db.locations;const top=all[0];const w=await weather(Number(req.query.lat||top?.lat||20.5937),Number(req.query.lon||top?.lon||78.9629));let locations=all.filter(l=>(!req.query.state||req.query.state==='All'||l.state===req.query.state)&&(!req.query.city||req.query.city==='All'||l.city===req.query.city)).map(l=>risk(l,w)).sort((a,b)=>b.riskScore-a.riskScore).map((l,i)=>({...l,rank:i+1}));res.json({locations,actions:db.actions,observations:db.observations,weather:w,updatedAt:db.updatedAt,coverage:'Partial; seed/demo and user-submitted records are labeled.'})});
app.get('/api/locations',(req,res)=>res.json(db.locations));app.get('/api/events',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders?.();res.write(`event: connected\ndata: ${JSON.stringify({at:iso()})}\n\n`);clients.add(res);const h=setInterval(()=>res.write(`event: heartbeat\ndata: ${JSON.stringify({at:iso()})}\n\n`),20000);req.on('close',()=>{clearInterval(h);clients.delete(res)})});
app.get('/api/observations',(_q,res)=>res.json(db.observations));
app.post('/api/observations',upload.array('photos',3),(req,res)=>{const b=req.body||{};const loc=db.locations.find(l=>l.id===clean(b.locationId,100));const lat=Number(b.lat??loc?.lat),lon=Number(b.lon??loc?.lon);if(!loc||!clean(b.type)||!validCoords(lat,lon))return res.status(400).json({error:'Valid location, type, and Indian coordinates are required.'});const observedAt=new Date(b.observedAt||Date.now());if(Number.isNaN(observedAt.getTime())||observedAt>Date.now()+300000)return res.status(400).json({error:'Invalid observation timestamp.'});const duplicate=db.observations.find(o=>o.locationId===loc.id&&o.type===clean(b.type,80)&&Date.now()-new Date(o.observedAt).getTime()<3600000);if(duplicate)return res.status(409).json({error:'A similar observation was already submitted within the last hour.'});const o={id:id(),locationId:loc.id,type:clean(b.type,80),severity:clean(b.severity||'moderate',20),lat,lon,blockageLevel:clamp(b.blockageLevel),visibleLitter:b.visibleLitter==='true',oilResidue:b.oilResidue==='true',constructionSediment:b.constructionSediment==='true',animalWaste:b.animalWaste==='true',waterBodyConnection:b.waterBodyConnection==='true',notes:clean(b.notes,2000),observedAt:observedAt.toISOString(),submittedAt:iso(),source:'User-submitted',coverage:clean(b.coverage||'Community reported',40),verification:'Pending',photos:(req.files||[]).map(f=>`/uploads/${f.filename}`)};db.observations.unshift(o);persist();emit('observation.created',o);emit('risk.recalculated',{locationId:loc.id});res.status(201).json(o)});
app.patch('/api/observations/:id/verify',(req,res)=>{const o=db.observations.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'Observation not found.'});const decision=['Verified','Rejected'].includes(req.body?.verification)?req.body.verification:null;if(!decision)return res.status(400).json({error:'Verification must be Verified or Rejected.'});o.verification=decision;o.reviewer=clean(req.body.reviewer||'Operator',100);o.verificationComment=clean(req.body.comment,1000);o.verifiedAt=iso();persist();emit('observation.verified',o);res.json(o)});
app.get('/api/actions',(_q,res)=>res.json(db.actions));app.post('/api/actions',(req,res)=>{const b=req.body||{},loc=db.locations.find(l=>l.id===b.locationId);if(!loc||!clean(b.type))return res.status(400).json({error:'Valid location and action type are required.'});const a={id:id(),locationId:loc.id,type:clean(b.type,100),priority:clean(b.priority||'High',20),status:'Pending',assignee:clean(b.assignee,120),dueBefore:b.dueBefore||null,notes:clean(b.notes,2000),evidence:[],history:[{status:'Pending',at:iso()}],createdAt:iso(),updatedAt:iso()};db.actions.unshift(a);persist();emit('action.updated',a);res.status(201).json(a)});
app.patch('/api/actions/:id',(req,res)=>{const a=db.actions.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Action not found.'});const statuses=['Pending','Assigned','In progress','Completed','Verified','Rejected'];if(req.body.status&&!statuses.includes(req.body.status))return res.status(400).json({error:'Unsupported status.'});if(req.body.status&&req.body.status!==a.status){a.status=req.body.status;a.history.push({status:a.status,at:iso(),comment:clean(req.body.comment,500)});if(a.status==='Completed')a.completedAt=iso()}a.assignee=clean(req.body.assignee??a.assignee,120);a.updatedAt=iso();persist();emit('action.updated',a);res.json(a)});
app.post('/api/actions/:id/evidence',upload.array('photos',3),(req,res)=>{const a=db.actions.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Action not found.'});a.evidence.push(...(req.files||[]).map(f=>({url:`/uploads/${f.filename}`,kind:clean(req.body.kind||'after',30),at:iso(),note:clean(req.body.note,500)})));a.updatedAt=iso();persist();emit('action.updated',a);res.json(a)});
app.post('/api/chat',(req,res)=>{const q=clean(req.body?.message,500).toLowerCase();const locations=db.locations.map(l=>risk(l,null)).sort((a,b)=>b.riskScore-a.riskScore);let answer,source='Current application data',mode='local-grounded';if(q.includes('pending')&&q.includes('verif'))answer=`${db.observations.filter(o=>o.verification==='Pending').length} observations are pending verification.`;else if(q.includes('which')||q.includes('first')||q.includes('inspect')){const x=locations[0];answer=`${x.name} is currently ranked first at ${x.riskScore}/100 (${x.level}). Main factors: ${x.reason} Recommended action: ${x.recommendation}`;}else if(q.includes('brief'))answer=`Field briefing: prioritize ${locations.slice(0,3).map(x=>`${x.name} (${x.riskScore}/100)`).join(', ')}. Confirm weather status before dispatch and record evidence after action.`;else {const x=locations.find(l=>q.includes(l.name.toLowerCase())||q.includes(l.id.toLowerCase()))||locations[0];answer=`${x.name} has an estimated relative risk of ${x.riskScore}/100 (${x.level}) with ${x.confidence} confidence. ${x.reason} This is not a laboratory contamination result.`}res.json({answer,mode,source})});
function csv(v){return `"${String(v??'').replaceAll('"','""')}"`}app.get('/api/report.csv',(req,res)=>{const rows=db.locations.map(l=>risk(l,null));const out=['rank,name,city,state,riskScore,level,confidence,coverage,recommendation',...rows.map((x,i)=>[i+1,x.name,x.city,x.state,x.riskScore,x.level,x.confidence,x.coverage,x.recommendation].map(csv).join(','))].join('\n');res.type('text/csv').set('Content-Disposition','attachment; filename="firstflush-priority.csv"').send(out)});app.get('/api/report.json',(_q,res)=>res.json({generatedAt:iso(),locations:db.locations.map(l=>risk(l,null)),actions:db.actions}));app.get('*',(_q,res)=>res.sendFile(path.join(root,'public/index.html')));app.use((e,_q,res,_n)=>res.status(500).json({error:'Request could not be processed.'}));
export {app}; export const handler=serverless(app); if(!process.env.AWS_LAMBDA_FUNCTION_NAME)app.listen(port,()=>console.log(`FirstFlush India running at http://localhost:${port}`));
